replicaCount: 2

image:
  repository: 448658572737.dkr.ecr.ap-southeast-1.amazonaws.com/target-frontend
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: ""
      paths:
        - path: /app(/|$)(.*)
          pathType: ImplementationSpecific
  tls:
    - secretName: frontend-tls
      hosts: []

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

env:
  BACKEND_URL: http://target-backend:5000
  NEXT_TELEMETRY_DISABLED: "1"

nodeSelector: {}
